version: '3'

services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    working_dir: /opt/node-app/docker-rabbitmq-sample
    volumes:
      - ./worker:/opt/node-app/docker-rabbitmq-sample
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://localhost
    links:
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    working_dir: /opt/node-app/docker-rabbitmq-sample
    volumes:
      - ./consumer:/opt/node-app/docker-rabbitmq-sample
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://localhost
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge            